### This is the authentication API endpoints doc

# Initialize the variables

@baseURL=http://localhost:5000/api/v1
@confirm_account_token = "put confirm account token here"
@reset_password_token="put reset password token here"

@username = "testing"
@password = "testTeSt10@"
@email = "testing@testing.com"

### sing-in endpoint
# endpoint : baseURL/auth/sign_in
# method : POST
# content-type : application/json
# body params :
    # username -> required | string 
    # password -> required | string
    # remember -> optional | boolean
POST {{baseURL}}/auth/sign_in
Content-Type: application/json

{
    "username":{{username}},
    "password":{{password}},
    "rememberMe":true
}


### sign-up endpoint
# endpoint : baseURL/auth/sign_up
# method : POST
# content-type : application/json
# body params :
    # username  -> required | string 
    # email     -> required | string
    # password  -> required | string
POST {{baseURL}}/auth/sign_up
Content-Type: application/json

{
    "username":{{username}},
    "email":{{email}},
    "password":{{password}}
}

### confirm-account endpoint
# endpoint : baseURL/auth/confirm_account
# method : POST
# content-type : application/json
# body params :
    # token     -> required | string
POST {{baseURL}}/auth/confirm_account
Content-Type: application/json

{  
     "token":{{confirm_account_token}}
}

### forgot-password endpoint
# endpoint : baseURL/auth/forgot_password
# method : POST
# content-type : application/json
# body params :
    # email     -> required | string
POST {{baseURL}}/auth/forgot_password
Content-Type: application/json

{
    "email":{{email}}
}

### reset-password endpoint
# endpoint : baseURL/auth/reset_password
# method : POST
# content-type : application/json
# body params :
    # token     -> required | string
    # password  -> required | string
POST {{baseURL}}/auth/reset_password
Content-Type: application/json

{
    "token":{{reset_password_token}},
    "password":{{password}}
}

### re-send confirmation endpoint
# endpoint : baseURL/auth/resend_confirmation
# method : POST
# content-type : application/json
# body params :
    # email     -> required | string

POST {{baseURL}}/auth/resend_confirmation
Content-Type: application/json

{
    "email":{{email}}
}

