# This is post API endpoints doc

# Initialize the variables
@baseURL = http://localhost:5000/api/v1

@access_token = "put access token here"


### create post 
# endpoint : baseURL/feed/posts
# method : POST
# content-type : application/json
# body params :
    # content      ->  required | string
    # isPrivate     ->  required | boolean

POST {{baseURL}}/feed/posts
x-auth-token : {{access_token}}
Content-Type: application/json

{
    "content":"Hello from http client",
    "isPrivate":false
}

### read post
# endpoint : baseURL/feed/posts/<postId>
# method : GET
GET {{baseURL}}/feed/posts/5fe3b6e17837fa711c6b4c32
x-auth-token : {{access_token}}

### delete post
# endpoint : baseURL/feed/posts/<postId>
# method : DELETE
DELETE  {{baseURL}}/feed/posts/5fe3970b1b43b63a5b353c27/
x-auth-token : {{access_token}}

### update post
# endpoint : baseURL/feed/posts/<postId>
# method : PUT
# content-type : application/json
# params :
    # content      ->  required | string
    # isPrivate     ->  required | boolean
PUT  {{baseURL}}/feed/posts/5fe3ab56c6b08962acb47e86
x-auth-token : {{access_token}}
Content-Type: application/json

{
    "content":"Update Post To New Value",
    "isPrivate":true

}

### read all feed posts
# endpoint : baseURL/feed/posts
# method : GET
# query :
    # limit      ->  optional | number | default=50 | max=100
    # offset     ->  optional | number | default=0
GET {{baseURL}}/feed/posts?offset=0&limit=100
x-auth-token: {{access_token}}

### add comment to post 
# endpoint : baseURL/feed/posts/<postId>/comments
# method : POST
# content-type: application/json
# params :
    # content   -> required | string
POST {{baseURL}}/feed/posts/5fe39e46de76724afb6f152e/comments
x-auth-token:{{access_token}}
Content-Type: application/json

{
    "content": "Last Comment"
}

### get all post comments
# endpoint : baseURL/feed/posts/<postId>/comments
# method : GET
# query :
    # limit      ->  optional | number | default=50 | max=100
    # offset     ->  optional | number | default=0
GET {{baseURL}}/feed/posts/5fe3ab56c6b08962acb47e86/comments?
x-auth-token:{{access_token}}

### get comment
# endpoint : baseURL/feed/posts/<postId>/comments/<commentId>
# method : GET
GET {{baseURL}}/feed/posts/5fe3abafc6b08962acb47e8e/comments/5fe3aeff14e0cc699101d936
x-auth-token:{{access_token}}

### update comment
# endpoint : baseURL/feed/posts/<postId>/comments/<commentId>
# method : PUT
# content-type: application/json
# params :
    # content -> required | string
PUT {{baseURL}}/feed/posts/5fe3abafc6b08962acb47e8e/comments/5fe3aeff14e0cc699101d936
x-auth-token:{{access_token}}
Content-Type: application/json

{
    "content":"Updated !"
}

### delete comment
# endpoint : baseURL/feed/posts/<postId>/comments/<commentId>
# method : DELETE
DELETE  {{baseURL}}/feed/posts/5fe3abafc6b08962acb47e8e/comments/5fe3aba9c6b08962acb47e8d
x-auth-token:{{access_token}}

### like post
# endpoint : baseURL/feed/posts/<postId>/like
# method : POST
POST  {{baseURL}}/feed/posts/5fe3abafc6b08962acb47e8e/like
x-auth-token:{{access_token}}