# This file will include all API's endpoints and info about them 


# All API's errors and successes response
    # [200] - Login Success : {code:2032 ,accessToken:"xxx.xxx.xx" ,user: {xx:xxx,xx:xx}}
    # [201] - Registered Success : {code:2062}
    # [200] - Forgot Password : {code:2013}
    # [200] - Reset Password  : {code:2029}
    # [200] - Resend Confirmation : {code:2051}
    # [404] - Account Not Exist : {code:1030 ,msg:"Account Not Exist and Not Registered Yet !"}
    # [401] - Account Not Confirmed : {code:1063 ,msg:"Account Not Confirmed Yet !"}
    # [401] - Authentication Failed : {code:1024 ,msg: "Invalid username/password !"}
    # [409] - Account Already Exist : {code:1092 ,msg: "Account Already Exist !"}
    # [401] - Token Expired : {code:1072 ,msg:"Unautherized !"}
    # [401] - Token Invalid : {code:1079 ,msg:"Unautherized !"}
    # [401] - Token Missed :  {code:1075 ,msg:"Unautherized !"}
    # [429] - Too Many Request : {code:1032 ,msg:"Too Many Request"}
    # [400 | 422] - Bad Request : {code:1049,msg:"Special Message !"}
    # [403] - Don't Have Permission : {code:1003,msg:"Unauthorized !"}


# Initialize the variables

@baseURL = http://localhost:5000/api/v1


### testing the not found error 

GET {{baseURL}}/bad_endpoints

### sing-in endpoint
# endpoint : baseURL/auth/sign_in
# method : POST
# content-type : application/json
# params :
    # username -> required | string 
    # password -> required | string
    # rememberMe -> optional | boolean
POST {{baseURL}}/auth/sign_in
Content-Type: application/json

{
    "username":"oumdoussa11",
    "password":"oumosuSSa1@",
    "rememberMe":false
}


### sign-up endpoint
# endpoint : baseURL/auth/sign_up
# method : POST
# content-type : application/json
# params :
    # username  -> required | string 
    # email     -> required | string
    # password  -> required | string
POST {{baseURL}}/auth/sign_up
Content-Type: application/json

{
    "username":"awbxking",
    "email":"abdo.sabani30@gmail.com",
    "password":"awbxKING30@"
}

### confirm-account endpoint
# endpoint : baseURL/auth/confirm_account
# method : POST
# content-type : application/json
# params :
    # token     -> required | string
@confirm_account_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcG9nODY0NDdAeDFwb3N0LmNvbSIsImlhdCI6MTYwNDk2MjMwMywiZXhwIjoxNjA1MDQ4NzAzfQ.wYMVdw3doIXipMxsqKl6EKYoI8oI5Z7VNmYCZQyvc5I"
POST {{baseURL}}/auth/confirm_account
Content-Type: application/json

{  
     "token":{{confirm_account_token}}
}

### forgot-password endpoint
# endpoint : baseURL/auth/forgot_password
# method : POST
# content-type : application/json
# params :
    # email     -> required | string
POST {{baseURL}}/auth/forgot_password
Content-Type: application/json

{
    "email":"bepog86447@x1post.com"
}

### reset-password endpoint
# endpoint : baseURL/auth/reset_password
# method : POST
# content-type : application/json
# params :
    # token     -> required | string
    # password  -> required | string
@reset_password_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJlcG9nODY0NDdAeDFwb3N0LmNvbSIsImlhdCI6MTYwNDk2MjQ1NiwiZXhwIjoxNjA0OTY0MjU2fQ.EtldkVcpBHU-l2qtoQ3XD5YY7zfYfgzaV-qY1PhqzeA"

POST {{baseURL}}/auth/reset_password
Content-Type: application/json

{
    "token":{{reset_password_token}},
    "password":"tesTING3@"
}

### re-send confirmation endpoint
# endpoint : baseURL/auth/resend_confirmation
# method : POST
# content-type : application/json
# params :
    # email     -> required | string

POST {{baseURL}}/auth/resend_confirmation
Content-Type: application/json

{
    "email":"abdo.sabani30@gmail.com"
}