# This file will include all API's endpoints and info about them 


# All API's errors and successes response
    # [200] - Login Success : {code:2032 ,accessToken:"xxx.xxx.xx" ,user: {xx:xxx,xx:xx}}
    # [201] - Registered Success : {code:2062}
    # [200] - Forgot Password Success : {code:2013}
    # [200] - Reset Password Succes : {code:2029}
    # [200] - Resend Confirmation Success : {code:2051}
    # [200] - Confirm Account Success : {code:2041}
    # [404] - Account Not Exist : {code:1030 ,msg:"Account Not Exist and Not Registered Yet !"}
    # [401] - Account Not Confirmed : {code:1063 ,msg:"Account Not Confirmed Yet !"}
    # [401] - Authentication Failed : {code:1024 ,msg: "Invalid username/password !"}
    # [409] - Account Already Exist : {code:1092 ,msg: "Account Already Exist !"}
    # [401] - Token Expired : {code:1072 ,msg:"Unautherized !"}
    # [401] - Token Invalid : {code:1079 ,msg:"Unautherized !"}
    # [401] - Token Missed :  {code:1075 ,msg:"Unautherized !"}
    # [401] - Token Already Used :  {code:1074 ,msg:"Unautherized !"}
    # [429] - Too Many Request : {code:1032 ,msg:"Too Many Request"}
    # [400 | 422] - Bad Request : {code:1049,msg:"Special Message !"}
    # [403] - Don't Have Permission : {code:1003,msg:"Unauthorized !"}
    # [404] - Post Not Found {code:1021,msg:"Post Not Found"}
    # [404] - Comment Not Found {code:1022,msg:"Comment Not Found !"}


# Initialize the variables

@baseURL = http://localhost:5000/api/v1

@access_token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF3YnhraW5nIiwiaWF0IjoxNjA4NzczMzk0LCJleHAiOjE2MDg4NTk3OTR9.YQu7Bsl4X2CKYsur7bNLTgoPN2uyXfAgyamNaaVqIuc
### testing the not found error 
GET {{baseURL}}/bad_endpoints

### sing-in endpoint
# endpoint : baseURL/auth/sign_in
# method : POST
# content-type : application/json
# params :
    # username -> required | string 
    # password -> required | string
    # remember -> optional | boolean
POST {{baseURL}}/auth/sign_in
Content-Type: application/json

{
    "username":"awbxking",
    "password":"awbxKING30@",
    "rememberMe":false
}


### sign-up endpoint
# endpoint : baseURL/auth/sign_up
# method : POST
# content-type : application/json
# params :
    # username  -> required | string 
    # email     -> required | string
    # password  -> required | string
POST {{baseURL}}/auth/sign_up
Content-Type: application/json

{
    "username":"awbxking",
    "email":"abdo.sabani30@gmail.com",
    "password":"awbxKING30@"
}

### confirm-account endpoint
# endpoint : baseURL/auth/confirm_account
# method : POST
# content-type : application/json
# params :
    # token     -> required | string
@confirm_account_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiZG8uc2FiYW5pMzBAZ21haWwuY29tIiwiaWF0IjoxNjA4NzczMTc1LCJleHAiOjE2MDg4NTk1NzV9.o0cknJT3YPPjd2TrGMurrh3SXWX_EjuxKewcOnTupcY"
POST {{baseURL}}/auth/confirm_account
Content-Type: application/json

{  
     "token":{{confirm_account_token}}
}

### forgot-password endpoint
# endpoint : baseURL/auth/forgot_password
# method : POST
# content-type : application/json
# params :
    # email     -> required | string
POST {{baseURL}}/auth/forgot_password
Content-Type: application/json

{
    "email":"abdo.sabani30@gmail.com"
}

### reset-password endpoint
# endpoint : baseURL/auth/reset_password
# method : POST
# content-type : application/json
# params :
    # token     -> required | string
    # password  -> required | string
@reset_password_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiZG8uc2FiYW5pMzBAZ21haWwuY29tIiwiaWF0IjoxNjA4NTkwMTEzLCJleHAiOjE2MDg1OTE5MTN9.rnoDwQ6HQL0jgEZW_3zS7DWDzgsavkp7OX4rx3I42O8"
POST {{baseURL}}/auth/reset_password
Content-Type: application/json

{
    "token":{{reset_password_token}},
    "password":"tesTING3@"
}

### re-send confirmation endpoint
# endpoint : baseURL/auth/resend_confirmation
# method : POST
# content-type : application/json
# params :
    # email     -> required | string

POST {{baseURL}}/auth/resend_confirmation
Content-Type: application/json

{
    "email":"abdo.sabani30@gmail.com"
}

### create post 
# endpoint : baseURL/feed/posts
# method : POST
# content-type : application/json
# params :
    # postBody      ->  required | string
    # isPrivate     ->  required | boolean
POST {{baseURL}}/feed/posts
x-auth-token : {{access_token}}
Content-Type: application/json

{
    "postBody":"Hello from http client",
    "isPrivate":false
}

### retrieve post
# endpoint : baseURL/feed/posts/<postId>
# method : GET
GET {{baseURL}}/feed/posts/5fe3b6e17837fa711c6b4c32
x-auth-token : {{access_token}}

### delete post
# endpoint : baseURL/feed/posts/<postId>
# method : DELETE
DELETE  {{baseURL}}/feed/posts/5fe3970b1b43b63a5b353c27/
x-auth-token : {{access_token}}

### update post
# endpoint : baseURL/feed/posts/<postId>
# method : PUT
# content-type : application/json
# params :
    # postBody      ->  required | string
    # isPrivate     ->  required | boolean
PUT  {{baseURL}}/feed/posts/5fe3abafc6b08962acb47e8e
x-auth-token : {{access_token}}
Content-Type: application/json

{
    "postBody":"Update Post To New Value",
    "isPrivate":false

}

### retrieve all feed posts
# endpoint : baseURL/feed/posts
# method : GET
# query :
    # limit      ->  optional | number | default=50 | max=100
    # offset     ->  optional | number | default=0
GET {{baseURL}}/feed/posts?offset=0&limit=100
x-auth-token: {{access_token}}

### add comment to post 
# endpoint : baseURL/feed/posts/<postId>/comments
# method : POST
# params :
    # commentBody   -> required | string
POST {{baseURL}}/feed/posts/5fe39e46de76724afb6f152e/comments
x-auth-token:{{access_token}}
Content-Type: application/json

{
    "commentBody": "Last Comment"
}

### get all post comments
# endpoint : baseURL/feed/posts/<postId>/comments
# method : GET
# query :
    # limit      ->  optional | number | default=50 | max=100
    # offset     ->  optional | number | default=0
GET {{baseURL}}/feed/posts/5fe3ab56c6b08962acb47e86/comments?
x-auth-token:{{access_token}}

### get comment
# endpoint : baseURL/feed/posts/<postId>/comments/<commentId>
# method : GET
GET {{baseURL}}/feed/posts/5fe3abafc6b08962acb47e8e/comments/5fe3aeff14e0cc699101d936
x-auth-token:{{access_token}}

### update comment
# endpoint : baseURL/feed/posts/<postId>/comments/<commentId>
# method : PUT
# params :
    # commentBody
PUT {{baseURL}}/feed/posts/5fe3abafc6b08962acb47e8e/comments/5fe3aeff14e0cc699101d936
x-auth-token:{{access_token}}
Content-Type: application/json

{
    "commentBody":"Updated !"
}

### delete comment
# endpoint : baseURL/feed/posts/<postId>/comments/<commentId>
# method : DELETE
DELETE  {{baseURL}}/feed/posts/5fe3abafc6b08962acb47e8e/comments/5fe3aba9c6b08962acb47e8d
x-auth-token:{{access_token}}